# Generated by Django 5.1.5 on 2025-02-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_order_trade_type_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
    ]
