# Generated by Django 5.1.5 on 2025-02-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_order_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='target_price_trigger',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
