# Generated by Django 5.1.5 on 2025-02-27 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_asset_yfinance_symbol'),
        ('trade', '0006_remove_portfolio_asset_remove_portfolio_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularorder',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='regularorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stoplossorder',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='stoplossorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='targetorder',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='targetorder',
            name='user',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('order_type', models.CharField(choices=[('market', 'Market Order'), ('limit', 'Limit Order'), ('stoploss_market', 'Stop-Loss Market Order'), ('stoploss_limit', 'Stop-Loss Limit Order'), ('target_market', 'Target Market Order'), ('target_limit', 'Target Limit Order')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('trade_duration', models.CharField(choices=[('intraday', 'Intraday'), ('longterm', 'Long-Term')], default='longterm', max_length=10)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('triggered', 'Triggered')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.asset')),
                ('linked_stoploss', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_order_stoploss', to='trade.order')),
                ('linked_target', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_order_target', to='trade.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CombinedOrder',
        ),
        migrations.DeleteModel(
            name='RegularOrder',
        ),
        migrations.DeleteModel(
            name='StopLossOrder',
        ),
        migrations.DeleteModel(
            name='TargetOrder',
        ),
    ]
