# Generated by Django 5.1.5 on 2025-03-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=12),
        ),
    ]
