# Generated by Django 5.1.5 on 2025-03-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('triggered', 'Triggered'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
