# Generated by Django 5.1.5 on 2025-03-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trade_duration',
            field=models.CharField(choices=[('intraday', 'Intraday'), ('longterm', 'Long-Term'), ('delivery', 'Delivery')], default='longterm', max_length=10),
        ),
    ]
