# Generated by Django 5.1.3 on 2024-12-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
