# Generated by Django 5.1.3 on 2025-01-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='yfinance_symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
