# Generated by Django 5.1.5 on 2025-01-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_asset_yfinance_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='angle_one_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
