# Generated by Django 5.1.5 on 2025-01-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_asset_angle_one_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_name',
            new_name='name',
        ),
    ]
