# Generated by Django 5.1.5 on 2025-01-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_asset_name_asset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='angle_one_token',
            new_name='smart_api_token',
        ),
    ]
