# Generated by Django 5.1.5 on 2025-01-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_rename_angle_one_token_asset_smart_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='net_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='percent_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
