# Generated by Django 5.1.5 on 2025-01-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_asset_net_change_asset_percent_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tradingview_symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
