# Generated by Django 5.1.5 on 2025-01-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_asset_symbol_alter_asset_tradingview_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='yfinance_symbol',
        ),
    ]
