# Generated by Django 5.1.3 on 2024-12-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_currency_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
