# Generated by Django 5.1.3 on 2025-01-04 04:44

import django.core.validators
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_temporaryuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address is already registered.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='password',
            field=models.CharField(max_length=128, validators=[user.models.validate_password]),
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is already taken.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and underscores.', regex='^\\w+$'), user.models.validate_non_space_string]),
        ),
    ]
