# Generated by Django 5.1.5 on 2025-01-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_asset_yfinance_symbol'),
        ('user', '0010_watchlist_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_asset',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='default_asset', to='market.asset'),
        ),
    ]
