# Generated by Django 5.1.5 on 2025-02-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_asset_yfinance_symbol'),
        ('user', '0011_account_default_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='default_asset',
            field=models.ForeignKey(blank=True, default=16, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_asset', to='market.asset'),
        ),
    ]
