# Generated by Django 5.1.5 on 2025-03-11 04:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import user.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_asset_yfinance_symbol'),
        ('user', '0013_portfolio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='user.account'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='portfolio', max_length=100, validators=[user.models.validate_non_space_string]),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='average_price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='total_value',
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weightage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='market.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'asset')},
            },
        ),
    ]
